import {CONFIG,COLORS,LINES,DEFAULTS} from './catalog.js';
import {buildLayout,rect,homography,validQuad,validCorners,wallCorners,unprojectQuad} from './geometry.js';
import {shareURL,readShare} from './share.js';
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const state=structuredClone(DEFAULTS);let THREE,OrbitControls,GLTFExporter,mergeGeometries,renderer,scene,camera,controls,group,layout,tex,ready=false,revision=0,arRevision=-1,arURL,exportCache;
let photo=new Image(),quad=[[.20,.20],[.76,.20],[.76,.74],[.20,.74]],photoBox={x:0,y:0,w:1,h:1},comparing=false,photoReady=false;
let editingShape=true,photoEditing='shape';
const status=t=>{$('status').textContent=t;};
const nf=(n,d=2)=>n.toLocaleString('es-CL',{maximumFractionDigits:d});
const size=()=>state.model==='brick'?state.brick:LINES[state.line].size;
function chooseQuad(){quad=state.model==='wall'?[[.20,.20],[.76,.20],[.76,.74],[.20,.74]]:[[.35,.38],[.65,.38],[.65,.49],[.35,.49]];}
function syncCatalog(){
 const colors=state.model==='brick'?{Natural:['Liso','Rasguñado','Rústico'],Arcilla:['Liso','Rasguñado','Rústico'],Envejecido:['Liso','Rasguñado','Rústico'],Siena:['Liso','Rasguñado','Rústico'],Chocolate:['Liso','Rasguñado','Rústico'],Marfil:['Liso','Rasguñado','Rústico'],'Gris Urbano':['Liso','Rasguñado','Rústico']}:LINES[state.line].colors;
 if(!colors[state.color])state.color=Object.keys(colors)[0];if(!colors[state.color].includes(state.finish))state.finish=colors[state.color][0];
 $('swatches').replaceChildren(...Object.keys(colors).map(c=>{const b=document.createElement('button');b.className='swatch'+(state.color===c?' active':'');b.style.setProperty('--swatch',COLORS[c]);b.title=c;b.setAttribute('aria-label',c);b.setAttribute('aria-pressed',state.color===c);b.onclick=()=>{state.color=c;syncCatalog();rebuild();};return b;}));
 $('color-name').textContent=state.color;$('finish').replaceChildren(...colors[state.color].map(f=>new Option(f,f)));$('finish').value=state.finish;
 $('piece-size').textContent=size().map(n=>nf(n*100,1)).join(' × ')+' cm · '+(state.model==='brick'?'Medidas de prueba':'Medidas nominales');
 $('wall-controls').hidden=state.model!=='wall';$('tile-controls').hidden=state.model==='brick';$('brick-controls').hidden=state.model!=='brick';
 $$('[data-model]').forEach(b=>{b.classList.toggle('active',b.dataset.model===state.model);b.setAttribute('aria-pressed',b.dataset.model===state.model);});
}
function currentLayout(){return state.model==='wall'?buildLayout(state,size()):{pieces:[{id:0,polys:[rect(0,0,size()[0],size()[1])],full:true,cx:size()[0]/2,cy:size()[1]/2,w:size()[0],h:size()[1],angle:0}],regions:[],area:size()[0]*size()[1],cuts:0};}
function dimensions(){return state.model==='wall'?[state.width,state.height]:size();}
function finishTexture(){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#888';ctx.fillRect(0,0,128,128);let seed=57;const rand=()=>((seed=(seed*16807)%2147483647)/2147483647);for(let i=0;i<4500;i++){const v=80+rand()*100;ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.fillRect(rand()*128,rand()*128,state.finish==='Rústico'?3:1,state.finish==='Rasguñado'?12:1);}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;return t;}
function pieceColor(id){return new THREE.Color(COLORS[state.color]).multiplyScalar(.9+((id*37+13)%101)/500);}
function extrude(poly,depth){const sh=new THREE.Shape(poly.map(p=>new THREE.Vector2(...p)));return new THREE.ExtrudeGeometry(sh,{depth,bevelEnabled:false,steps:1});}
function releaseGroup(){if(!group)return;const geoms=new Set(),mats=new Set();group.traverse(o=>{if(o.geometry)geoms.add(o.geometry);if(o.material)mats.add(o.material);});geoms.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());scene.remove(group);tex?.dispose();}
function buildThree(){
 releaseGroup();group=new THREE.Group();tex=finishTexture();const [W,H]=dimensions(),depth=size()[2];const material=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.93,bumpMap:tex,bumpScale:state.finish==='Liso'?.00015:state.finish==='Rústico'?.0013:.0007});
 const full=layout.pieces.filter(p=>p.full),cuts=layout.pieces.filter(p=>!p.full),box=new THREE.BoxGeometry(1,1,1),dummy=new THREE.Object3D();
 if(full.length){const mesh=new THREE.InstancedMesh(box,material,full.length);full.forEach((p,i)=>{dummy.position.set(p.cx-W/2,p.cy-H/2,depth/2);dummy.rotation.set(0,0,p.angle);dummy.scale.set(p.w,p.h,depth);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,pieceColor(p.id));});mesh.instanceMatrix.needsUpdate=true;mesh.computeBoundingSphere();group.add(mesh);}else box.dispose();
 if(cuts.length){const gs=[];for(const p of cuts)for(const poly of p.polys){const g=extrude(poly,depth);g.translate(-W/2,-H/2,0);const col=pieceColor(p.id),a=new Float32Array(g.attributes.position.count*3);for(let i=0;i<a.length;i+=3){a[i]=col.r;a[i+1]=col.g;a[i+2]=col.b;}g.setAttribute('color',new THREE.BufferAttribute(a,3));gs.push(g);}const merged=mergeGeometries(gs);gs.forEach(g=>g.dispose());const cutMat=material.clone();cutMat.vertexColors=true;group.add(new THREE.Mesh(merged,cutMat));}
 if(state.model==='wall'){const gs=layout.regions.filter(p=>p.length>2).map(p=>{const g=extrude(p,.005);g.translate(-W/2,-H/2,-.005);return g;});const merged=mergeGeometries(gs);gs.forEach(g=>g.dispose());group.add(new THREE.Mesh(merged,new THREE.MeshStandardMaterial({color:state.mortar,roughness:1})));}
 if(state.model==='brick'&&$('brick-type').value==='grooved'){const gm=new THREE.MeshStandardMaterial({color:COLORS[state.color],roughness:1});const ribGeo=new THREE.BoxGeometry(.003,H*.8,.0015);for(let x=-W/2+.02;x<W/2;x+=.025){const rib=new THREE.Mesh(ribGeo,gm);rib.position.set(x,0,depth+.0005);group.add(rib);}}
 group.name='CeramicaSantiago_'+state.model;scene.add(group);exportCache=null;
 // TODO: REEMPLAZAR AQUÍ CON MODELO GLB REAL. Ver assets/README.md antes de
 // normalizar una geometría cargada con GLTFLoader a metros e instanciarla.
 // TODO: TEXTURAS PBR REALES: TextureLoader + CONFIG.paths.textures; color sRGB.
}
function frame(){if(!ready)return;const [w,h,d=.03]=dimensions(),radius=Math.max(w,h,d),aspect=$('stage').clientWidth/$('stage').clientHeight;const distance=Math.max(h,w/aspect)*2.15;camera.near=.001;camera.far=100;const front=state.model==='wall'&&editingShape;camera.position.set(front?0:radius*(state.model==='wall'?.3:.8),front?0:radius*(state.model==='wall'?.2:.55),distance);controls.target.set(0,0,0);controls.minDistance=radius*.2;controls.maxDistance=radius*8;camera.updateProjectionMatrix();controls.update();syncShapeEditor();}
function rebuild(){
 try{layout=currentLayout();revision++;if(ready)buildThree();$('stat-area').innerHTML=nf(state.model==='wall'?layout.area:size()[0]*100)+(state.model==='wall'?' <small>m²</small>':' <small>cm de largo</small>');$('stat-label').textContent=state.model==='wall'?'SUPERFICIE NETA':'DIMENSIÓN';$('stat-count').textContent=nf(layout.pieces.length,0);$('result-note').innerHTML=state.model==='wall'?`${layout.cuts} piezas con corte.<br>Estimación visual, sin merma.`:'Pieza de referencia.<br>Acabado ilustrativo.';$('scene-label').textContent={wall:'MURO DE ENCHAPE',tile:'ENCHAPE INDIVIDUAL',brick:'LADRILLO · MODELO DE PRUEBA'}[state.model];$('dimension-badge').textContent=dimensions().slice(0,2).map(n=>nf(n*(state.model==='wall'?1:100))).join(' × ')+(state.model==='wall'?' m':' cm');$('joint-note').hidden=state.joint<=.01;$('opening-fields').hidden=!state.opening;drawPhoto();if(state.mode==='ar')prepareAR();}catch(e){status(e.message);}
}
function scenePhoto(){photoReady=false;photo.onload=()=>{photoReady=true;drawPhoto();};photo.onerror=()=>status('No se pudo cargar el ambiente de ejemplo.');photo.src=CONFIG.paths.environments+'ambiente-demo.svg';}
function drawPhoto(){if(state.mode!=='photo'||!photoReady||!layout)return;const c=$('photo-canvas'),r=$('stage').getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);c.width=r.width*dpr;c.height=r.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#e8e5dd';ctx.fillRect(0,0,r.width,r.height);const scale=Math.min(r.width/photo.width,r.height/photo.height);photoBox={x:(r.width-photo.width*scale)/2,y:(r.height-photo.height*scale)/2,w:photo.width*scale,h:photo.height*scale};const {x,y,w,h}=photoBox;ctx.drawImage(photo,x,y,w,h);const q=quad.map(p=>[x+p[0]*w,y+p[1]*h]),map=homography(q),[W,H]=dimensions();
 const path=poly=>{ctx.beginPath();poly.forEach(([a,b],i)=>{const p=map(a/W,1-b/H);i?ctx.lineTo(...p):ctx.moveTo(...p);});ctx.closePath();};
 if(!comparing){ctx.globalAlpha=state.opacity;if(state.model==='wall'){ctx.fillStyle=state.mortar;layout.regions.forEach(p=>{path(p);ctx.fill();});}layout.pieces.forEach(p=>{const color=COLORS[state.color],factor=.9+((p.id*37+13)%101)/500;const rgb=[1,3,5].map(i=>Math.min(255,Math.round(parseInt(color.slice(i,i+2),16)*factor)));ctx.fillStyle=`rgb(${rgb})`;p.polys.forEach(poly=>{path(poly);ctx.fill();ctx.save();ctx.clip();ctx.strokeStyle='rgba(40,20,10,.1)';ctx.lineWidth=state.finish==='Rústico'?1.5:.5;const center=map(p.cx/W,1-p.cy/H);if(state.finish!=='Liso'){for(let k=-3;k<4;k++){ctx.beginPath();ctx.moveTo(center[0]-40,center[1]+k*2);ctx.lineTo(center[0]+40,center[1]+k*2+.5);ctx.stroke();}}ctx.restore();});});ctx.globalAlpha=1;}
 const positions=state.model==='wall'&&photoEditing==='shape'?wallCorners(state).map(p=>map(...p)):q;
 $$('.pin').forEach((b,i)=>{b.style.left=positions[i][0]+'px';b.style.top=positions[i][1]+'px';b.hidden=comparing;});
}
function isShapeEditing(){return state.model==='wall'&&(state.mode==='3d'?editingShape:state.mode==='photo'&&photoEditing==='shape');}
function syncShapeEditor(){
 const wall=state.model==='wall',active=isShapeEditing();
 $('shape-tools').hidden=!wall;$('photo-perspective').hidden=state.mode!=='photo';
 $('edit-shape').textContent=state.mode==='ar'?'Editar forma · volver al 3D':state.mode==='3d'&&editingShape?'Terminar edición · girar 3D':'Editar forma · 4 puntos';
 $('edit-shape').setAttribute('aria-pressed',active);$('photo-perspective').setAttribute('aria-pressed',photoEditing==='perspective');
 $('shape-mode-note').textContent=state.mode==='photo'&&photoEditing==='perspective'?'Solo cambia el encuadre de la foto.':'Este contorno se conserva en 3D, QR y AR.';
 $('pins').hidden=!(active||state.mode==='photo');
 if(controls)controls.enabled=!(state.mode==='3d'&&active);
 $('stage-hint').textContent=active?'Mueve las 4 esquinas · Esta forma se conserva en AR':state.mode==='photo'?'Ajusta la perspectiva · No cambia la forma del muro':state.mode==='ar'?'Se coloca la forma editada · AR en teléfonos compatibles':'↔ Arrastra para girar · Desliza para acercar';
 if(state.mode==='3d'&&active&&ready){camera.updateMatrixWorld();const r=$('stage').getBoundingClientRect();wallCorners(state).forEach(([u,v],i)=>{const p=new THREE.Vector3((u-.5)*state.width,(.5-v)*state.height,size()[2]).project(camera),b=$$('.pin')[i];b.hidden=false;b.style.left=(p.x+1)*r.width/2+'px';b.style.top=(1-p.y)*r.height/2+'px';});}
 if(wall)$('shape').value=state.shape;
}
function applyCorner(i,p){
 const q=wallCorners(state);q[i]=p.map(v=>Math.round(Math.max(0,Math.min(1,v))*10000)/10000);
 if(!validCorners(q)){status('Mantén las esquinas en orden, sin cruzarlas ni cerrar el muro.');return;}
 state.shape='custom';state.corners=q;rebuild();syncShapeEditor();status('Forma actualizada. El QR y AR usarán este mismo contorno.');
}
for(let i=0;i<4;i++){
 const b=document.createElement('button');b.className='pin';b.textContent=i+1;b.setAttribute('aria-label',`Esquina ${i+1}. Usa las flechas para moverla.`);$('pins').append(b);
 b.onpointerdown=e=>{e.preventDefault();b.focus();b.setPointerCapture(e.pointerId);};
 b.onpointermove=e=>{if(!b.hasPointerCapture(e.pointerId))return;const r=$('stage').getBoundingClientRect();
 if(isShapeEditing()){
 let p;if(state.mode==='3d'){const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);const hit=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,0,1),-size()[2]),new THREE.Vector3());if(!hit)return;p=[hit.x/state.width+.5,.5-hit.y/state.height];}
 else p=unprojectQuad(quad,(e.clientX-r.left-photoBox.x)/photoBox.w,(e.clientY-r.top-photoBox.y)/photoBox.h);
 applyCorner(i,p);
 }else{const q=structuredClone(quad);q[i]=[Math.max(0,Math.min(1,(e.clientX-r.left-photoBox.x)/photoBox.w)),Math.max(0,Math.min(1,(e.clientY-r.top-photoBox.y)/photoBox.h))];if(validQuad(q)){quad=q;drawPhoto();}}
 };
 b.onpointerup=e=>{if(b.hasPointerCapture(e.pointerId))b.releasePointerCapture(e.pointerId);};
 b.onkeydown=e=>{const d={ArrowLeft:[-.01,0],ArrowRight:[.01,0],ArrowUp:[0,-.01],ArrowDown:[0,.01]}[e.key];if(!d)return;e.preventDefault();if(isShapeEditing()){const p=wallCorners(state)[i];applyCorner(i,p.map((v,j)=>v+d[j]*(e.shiftKey?5:1)));}else{const q=structuredClone(quad);q[i]=q[i].map((v,j)=>Math.max(0,Math.min(1,v+d[j])));if(validQuad(q)){quad=q;drawPhoto();}}};
}
$('edit-shape').onclick=()=>{if(state.mode==='ar'){editingShape=true;setMode('3d');frame();}else if(state.mode==='3d'){editingShape=!editingShape;frame();}else{photoEditing='shape';syncShapeEditor();drawPhoto();}};
$('photo-perspective').onclick=()=>{photoEditing='perspective';syncShapeEditor();drawPhoto();};
$('reset-shape').onclick=()=>{state.shape='rectangle';state.corners=structuredClone(DEFAULTS.corners);rebuild();syncShapeEditor();status('Forma rectangular restablecida en todas las vistas.');};
function setMode(mode){state.mode=mode;$$('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',b.dataset.mode===mode);});$('three-view').hidden=mode!=='3d';$('photo-canvas').hidden=mode!=='photo';$('photo-tools').hidden=mode!=='photo';$('ar-view').hidden=mode!=='ar';$('primary-action').textContent=mode==='3d'?'Probar en mi foto ↗':mode==='photo'?'Guardar imagen ↓':'Descargar modelo ↓';$('save-png').disabled=mode==='ar';syncShapeEditor();if(mode==='photo'){drawPhoto();status(state.model==='wall'?'Los puntos editan la forma real. Usa «Ajustar perspectiva» para encuadrarla en tu foto.':'Sube tu foto y ajusta su encuadre.');}else if(mode==='ar'){prepareAR();}else{frame();status(isShapeEditing()?'Edita las esquinas del muro. Su forma se conserva al pasar a AR.':'Arrastra el modelo para explorar sus dimensiones.');}}
async function exportGLB(){if(!ready)throw Error('La vista 3D aún no está lista.');if(exportCache)return exportCache;
 // Bake instances into ordinary merged meshes: native AR need not support GPU instancing.
 const out=new THREE.Group(),geometries=[],materials=[];group.updateMatrixWorld(true);group.children.forEach(o=>{if(!o.isMesh)return;const gs=[];if(o.isInstancedMesh){const m=new THREE.Matrix4(),color=new THREE.Color();for(let i=0;i<o.count;i++){o.getMatrixAt(i,m);const g=o.geometry.clone().toNonIndexed();g.applyMatrix4(m);o.getColorAt(i,color);const a=new Float32Array(g.attributes.position.count*3);for(let k=0;k<a.length;k+=3){a[k]=color.r;a[k+1]=color.g;a[k+2]=color.b;}g.setAttribute('color',new THREE.BufferAttribute(a,3));gs.push(g);}}else{const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(o.matrix);gs.push(g);}const merged=mergeGeometries(gs);gs.forEach(g=>g.dispose());const mat=o.material.clone();mat.vertexColors=!!merged.attributes.color;const mesh=new THREE.Mesh(merged,mat);out.add(mesh);geometries.push(merged);materials.push(mat);});out.position.y=dimensions()[1]/2;out.updateMatrixWorld(true);
 const rev=revision;try{const data=await new GLTFExporter().parseAsync(out,{binary:true,onlyVisible:true});if(rev===revision)exportCache=data;return data;}finally{geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}
}
let arPreparing=false;
async function prepareAR(){if(!ready||arPreparing)return;if(arRevision===revision)return;arPreparing=true;const rev=revision;$('ar-loading').hidden=false;$('ar-model').style.opacity='0';try{await loadModelViewer();const data=await exportGLB();if(rev!==revision)return;const next=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'}));if(arURL)URL.revokeObjectURL(arURL);arURL=next;const mv=$('ar-model');mv.setAttribute('ar-placement',state.model==='brick'?'floor':'wall');mv.src=arURL;arRevision=revision;status('Modelo preparado. En un teléfono compatible, usa «Colocar en mi espacio». En escritorio puedes inspeccionar el modelo.');}catch(e){$('ar-loading').textContent='No pudimos preparar AR. Puedes seguir usando la vista 3D.';status('AR: '+e.message);}finally{arPreparing=false;if(rev!==revision&&state.mode==='ar')prepareAR();}}
let modelViewerPromise;
function loadModelViewer(){return modelViewerPromise??=new Promise((resolve,reject)=>{const s=document.createElement('script');s.type='module';s.src='https://cdn.jsdelivr.net/npm/@google/model-viewer@4.1.0/dist/model-viewer.min.js';s.onload=()=>customElements.whenDefined('model-viewer').then(resolve);s.onerror=()=>{modelViewerPromise=null;reject(Error('No se pudo descargar el visor AR.'));};document.head.append(s);});}
$('ar-model').addEventListener('load',()=>{$('ar-loading').hidden=true;$('ar-model').style.opacity='1';if(!$('ar-model').canActivateAR)status('Este dispositivo no ofrece AR. Puedes explorar el modelo 3D y abrir esta página con HTTPS en un teléfono compatible.');});$('ar-model').addEventListener('error',()=>{arRevision=-1;$('ar-loading').textContent='El visor no pudo abrir el modelo. Cambia a Vista 3D y vuelve a intentarlo.';});$('ar-model').addEventListener('ar-status',e=>{if(e.detail.status==='failed')status('No se pudo iniciar AR. Comprueba los permisos de cámara y la compatibilidad del teléfono.');});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function saveGLB(){const b=$('save-glb');b.disabled=true;status('Preparando modelo 3D…');try{download(new Blob([await exportGLB()],{type:'model/gltf-binary'}),'ceramica-santiago.glb');status('Modelo GLB preparado para descargar a escala real, en metros.');}catch(e){status(e.message);}finally{b.disabled=false;}}
function savePNG(){if(state.mode==='ar')return;if(state.mode==='3d'&&!ready)return;const c=state.mode==='photo'?$('photo-canvas'):renderer.domElement;if(state.mode==='3d')renderer.render(scene,camera);c.toBlob(blob=>{if(blob){download(blob,'mi-proyecto-ceramica.png');status('Imagen preparada para descargar.');}else status('No se pudo generar la imagen.');},'image/png');}
$$('[data-model]').forEach(b=>b.onclick=()=>{state.model=b.dataset.model;chooseQuad();syncCatalog();rebuild();frame();});$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-pattern]').forEach(b=>b.onclick=()=>{state.pattern=b.dataset.pattern;$$('[data-pattern]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});rebuild();});
for(const id of ['line','finish','width','height','joint','mortar','shape','cut','offset','opening','openingWidth','openingHeight']){$(id).addEventListener('change',e=>{const input=e.target;if(input.type==='number'&&(!input.value||!input.checkValidity())){input.value=state[id];status('Usa un valor dentro del rango permitido.');return;}state[id]=input.type==='checkbox'?input.checked:['width','height','joint','offset','openingWidth','openingHeight'].includes(id)?Number(input.value):input.value;if(id==='line'||id==='finish')syncCatalog();rebuild();if(['width','height'].includes(id))frame();});}
for(const [i,id] of ['brick-x','brick-y','brick-z'].entries())$(id).onchange=e=>{if(!e.target.value||!e.target.checkValidity()){e.target.value=state.brick[i]*100;return;}state.brick[i]=Number(e.target.value)/100;syncCatalog();rebuild();frame();};$('brick-type').onchange=()=>rebuild();$('opacity').oninput=e=>{state.opacity=Number(e.target.value);drawPhoto();};
$('reset-view').onclick=()=>{chooseQuad();frame();drawPhoto();if(state.mode==='ar'){$('ar-model').cameraOrbit='auto auto auto';$('ar-model').fieldOfView='auto';}status('Vista restablecida.');};$('primary-action').onclick=()=>state.mode==='3d'?setMode('photo'):state.mode==='photo'?savePNG():saveGLB();$('save-glb').onclick=saveGLB;$('save-png').onclick=savePNG;$('save-project').onclick=()=>{download(new Blob([JSON.stringify({schemaVersion:1,state,brickType:$('brick-type').value,photoCorners:quad,photoIncluded:false},null,2)],{type:'application/json'}),'proyecto-ceramica.json');status('Configuración descargada; no incluye tu fotografía.');};$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();$('demo-photo').onclick=()=>{chooseQuad();scenePhoto();};$('compare').onclick=()=>{comparing=!comparing;$('compare').textContent=comparing?'Ver revestimiento':'Ver original';$('compare').setAttribute('aria-pressed',comparing);drawPhoto();};
$('photo-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>CONFIG.maxPhotoBytes){status('Selecciona una imagen JPG, PNG o WebP de hasta 20 MB.');e.target.value='';return;}try{const bitmap=await createImageBitmap(f,{imageOrientation:'from-image'}),c=document.createElement('canvas'),scale=Math.min(1,2400/Math.max(bitmap.width,bitmap.height));c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const next=new Image();await new Promise((resolve,reject)=>{next.onload=resolve;next.onerror=reject;next.src=c.toDataURL('image/jpeg',.92);});photo=next;photoReady=true;chooseQuad();comparing=false;$('compare').textContent='Ver original';drawPhoto();status('Foto lista. Se procesa localmente y no se envía a un servidor.');}catch{status('No pudimos leer esa imagen. Prueba con otro archivo.');}e.target.value='';};
let sharedProject;
try{sharedProject=readShare(location.hash);if(sharedProject){Object.assign(state,sharedProject.state);$('brick-type').value=sharedProject.brickType;for(const id of ['line','finish','width','height','joint','mortar','shape','cut','offset','opening','openingWidth','openingHeight']){if($(id).type==='checkbox')$(id).checked=state[id];else $(id).value=state[id];}['brick-x','brick-y','brick-z'].forEach((id,i)=>$(id).value=state.brick[i]*100);$$('[data-pattern]').forEach(b=>b.classList.toggle('active',b.dataset.pattern===state.pattern));chooseQuad();}}catch{status('El enlace compartido no es válido. Se abrió el diseño inicial.');}
syncCatalog();rebuild();scenePhoto();
if(sharedProject){setMode('ar');status('Diseño compartido cargado. Preparando la vista para tu dispositivo…');}
$('share-qr').onclick=async()=>{const url=shareURL(location.href,state,$('brick-type').value);$('share-link').value=url;$('qr-dialog').showModal();$('qr-message').textContent=location.protocol==='https:'?'Escanea con la cámara del teléfono. Abrirá este diseño y preparará AR.':'Este enlace es local. El QR funcionará entre dispositivos desde la dirección HTTPS de Firebase.';try{const {default:QRCode}=await import('./vendor/qrcode.js');await QRCode.toCanvas($('qr-canvas'),url,{width:320,margin:3,errorCorrectionLevel:'M',color:{dark:'#252821',light:'#ffffff'}});}catch{$('qr-message').textContent='No se pudo generar el QR. Copia el enlace para abrirlo en tu teléfono.';}};
$('close-qr').onclick=()=>$('qr-dialog').close();$('copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('share-link').value);$('qr-message').textContent='Enlace copiado. La foto no se incluye en el enlace.';}catch{$('share-link').select();$('qr-message').textContent='Selecciona y copia el enlace con el menú del navegador.';}};
$('save-qr').onclick=()=>$('qr-canvas').toBlob(b=>{if(b)download(b,'ceramica-santiago-qr.png');});
async function init(){try{[THREE,{OrbitControls},{GLTFExporter},{mergeGeometries}]=await Promise.all([import('three'),import('three/addons/controls/OrbitControls.js'),import('three/addons/exporters/GLTFExporter.js'),import('three/addons/utils/BufferGeometryUtils.js')]);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;$('three-view').append(renderer.domElement);scene=new THREE.Scene();scene.add(new THREE.HemisphereLight(0xfff7e8,0x9b998b,2.4));const key=new THREE.DirectionalLight(0xfff7ef,3.2);key.position.set(-3,4,5);scene.add(key);const fill=new THREE.DirectionalLight(0xeaf0ff,1);fill.position.set(4,1,2);scene.add(fill);camera=new THREE.PerspectiveCamera(36,1,.001,100);camera.position.set(0,0,5);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;ready=true;const resize=()=>{const {clientWidth:w,clientHeight:h}=$('stage');renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();drawPhoto();};new ResizeObserver(resize).observe($('stage'));resize();buildThree();frame();renderer.setAnimationLoop(()=>{if(state.mode==='3d'&&!document.hidden){controls.update();renderer.render(scene,camera);}});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();status('Se interrumpió la vista 3D. Recarga la página para recuperarla.');});if(state.mode==='ar')prepareAR();}catch(e){$('fatal').hidden=false;status('La vista 3D necesita WebGL y acceso al CDN. El montaje sobre foto sigue disponible. '+e.message);}}
init();


